title: Express-mongoose-es6-rest-api
description: "A boilerplate application for building RESTful APIs Microservice in Node.js using express and mongoose in ES6 with code coverage and JsonWebToken Authentication"
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
